[window]
# Matches your 100c x 30c size
dimensions = { columns = 100, lines = 30 }
# Alacritty handles opacity, but blur is still a Hyprland task
opacity = 1.0 
decorations = "none"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
size = 11.0

[cursor]
style = { shape = "Block", blinking = "Always" }
# Note: Alacritty doesn't have a built-in "hollow unfocused" 
# setting as simple as Kitty's, it usually stays as a block.

[colors.primary]
background = "#1b1e28"
foreground = "#a6accd"

[colors.normal]
black   = "#1b1e28"
red     = "#d0679d"
green   = "#5de4c7"
yellow  = "#fffac2"
blue    = "#add7ff"
magenta = "#f087bd"
cyan    = "#00ced1"
white   = "#a6accd"

[colors.bright]
black   = "#303340"
red     = "#d0679d"
green   = "#5de4c7"
yellow  = "#fffac2"
blue    = "#add7ff"
magenta = "#f087bd"
cyan    = "#00ced1"
white   = "#e4f0fb"

[terminal.shell]
program = "/bin/zsh" # Assuming you use zsh based on common Arch setups
