[LVDS-1.1]
apply-to = ["1"]
path = "/home/baselash/.config/wpaperd/Wallpapers/Arch-Wallpaper.jpg"

[LVDS-1.3]
apply-to = ["3"]
path = "/home/baselash/.config/wpaperd/wallpapers/Web-Wallpaper.jpg"

[LVDS-1.5]
apply-to = ["5"]
path = "/home/baselash/.config/wpaperd/wallpapers/Database-Wallpaper.jpg"

[LVDS-1.7]
apply-to = ["7"]
path = "/home/baselash/.config/wpaperd/wallpapers/Work-Wallpaper.jpg"

[LVDS-1.9]
apply-to = ["9"]
path = "/home/baselash/.config/wpaperd/wallpapers/Computer-Hardware-Wallpaper.jpg"

[VGA-1.2]
apply-to = ["2"]
path = "/home/baselash/.config/wpaperd/wallpapers/Programming-Wallpaper.png"

[VGA-1.4]
apply-to = ["4"]
path = "/home/baselash/.config/wpaperd/wallpapers/Server-Wallpaper.jpg"

[VGA-1.6]
apply-to = ["6"]
path = "/home/baselash/.config/wpaperd/wallpapers/Study-Wallpaper.jpg"

[VGA-1.8]
apply-to = ["8"]
path = "/home/baselash/.config/wpaperd/wallpapers/Social-Wallpaper.jpg"

[VGA-1.10]
apply-to = ["10"]
path = "/home/baselash/.config/wpaperd/wallpapers/Audio-Wallpaper.png"
